plugins:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rubocop-shopify: rubocop.yml

Layout/LineLength:
  Max: 160
Lint/MissingSuper:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/SymbolProc:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/ClassMethodsDefinitions:
  Enabled: false
Naming/InclusiveLanguage:
  Enabled: false
Naming/PredicateMethod:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/BeEq:
  Enabled: false
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/ExampleLength:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/ExpectInHook:
  Enabled: false
RSpec/IndexedLet:
  Enabled: false
