# This is a basic workflow to help you get started with Actions

name: "CI"

# Controls when the workflow will run
on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
      - run: bundle exec rubocop --format simple
